### ISSUE TITLE
유세윤 산소호흡기 프로젝트

### ISSUE THREAD

**Issue by Luavis** [ssuoss/HelloSSU#7]
희덕님이 졸업하면서 유세윤을 접으셨는데요. 그래서 최근에 유사 프로그램을 만드는 개인프로젝트를 진행중이였는데요 이 organization에서 공동으로 개발했으면 좋을거 같습니다.
## Features
- Web platform(with flask, python)
- TImetable crawler(with phantomjs 1.9, nodejs)

**Comment by ghost** [comment]
정말 좋은생각! 학생들의 불편도 줄이면서 꽤 롱런 할 수 있는 프로젝트가 되겠네요.

프로젝트 자체에는 참여를 안하시겠지만, 희덕님도 이곳에 초대를 드렸으니 가끔 구경하시면서 조언정도는 주실수도 있을 것 같구요.

적절한 Repo이름 혹은 프로젝트명을 알려주시면 제가 레포 생성하고 바로 Admin권한 드릴게요.
더불어 해당 프로젝트에 대한 Team도 설정해드리겠습니다.

**Comment by ghost** [comment]
성일님.
혹시 정통전의 소모임(전자전시회, 로보틱스 등등)이나 주변에 개발로 밥벌어먹고 살겠다는 사람이 좀 있나요?
그런 포부가 있는 사람들에게 이곳을 알려주시면 좋겠습니다~

**Comment by SSUHan** [comment]
동감입니다. 이와 관련해서 저도 14년도 IT대학 컴퓨터학부 소프트웨어 공모전 작품을 낸 경험이 있는데요.
학교 학생들이 편리하게 사용할 수 있는 "학교서비스어플리케이션" 은 우리학교 개발자나 개발자준비생들이 함께 관리하고 유지할 필요가 있다고 생각합니다~ :)
더 나아가 이 활동이 다른 학교의 IT학부들에게 좋은 귀감이 된다면 더욱 멋진일이 될 것 같습니다.

**Comment by toughrogrammer** [comment]
유어슈 오시지 허허

**Comment by toughrogrammer** [comment]
https://github.com/shlee322/timetable

유세윤에서 시간표만이 문제라면 제 친구가 열심히 작업했던게 있는데 이런거 포크 떠서 해보시면 어떠실지 ^^;

**Comment by ghost** [comment]
사실 시간표는 에브리타임이라는 서비스로도 충분히 잘 학우들이 사용하고있고, 또 그쪽이 잘 서비스하고 있다고 생각하네요.

시간표를 정말 다시만든다면 강의평가와 연동이 잘되어 있는 형태로 개발하면 괜찮지 않을까하네요.

2015년 9월 23일 오후 6:51, Luavis notifications@github.com님이 작성:

> 희덕님이 졸업하면서 유세윤을 접으셨는데요. 그래서 최근에 유사 프로그램을 만드는 개인프로젝트를 진행중이였는데요 이
> organization에서 공동으로 개발했으면 좋을거 같습니다.
> Features
> - Web platform(with flask, python)
> - TImetable crawler(with phantomjs 1.9, nodejs)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ssuoss/HelloSSU/issues/7.

## 

Ministry of National Defence R&D Engineer

Jongchan Kim

+82-10-9781-0031 (Mobile)

**Comment by Luavis** [comment]
에브리타임 사용중에 있는데요 생각보다 레이아웃 짤림문제가 심각하다고 생각해서...

희희덕덕님도 인수인계 포기하시고 프로젝트 자체를 drop하는 형식이셔서 포기하고 제작하지 않으려 했는데,
에브리타임의 짤림 현상은 생각보다 심각하더군요.

그리고 서버는 3년정도 아마존 서버를 무료로 사용할 수 있으니 이것을 사용하여 deploy할 계획입니다.

여태까지 작업한 timetable 관련 소스고요, [click](https://github.com/Luavis/timetable)

지금 막힌 부분이 시간표를 phantomjs를 이용해서 불러오는 부분인데, 이 부분도 고수님의 소견이 절실해 보입니다.

그리고 프로젝트 이름은 유세윤을 이어간다는 의미로 개코원숭이의 영어인 Papio로 하는게 어떨까 싶습니다만..

P.S.
phantomjs 에서 u-saint frame때문에 미치겠어요.. 제가 여태까지 짜본 소스 [공유](https://gist.github.com/Luavis/59ac6fc001cefa86417f)해봅니다.

**Comment by Luavis** [comment]
@Acegugu 님 혹시 있으면 추천해두겠습니다.

**Comment by toughrogrammer** [comment]
걍 패킷 스니핑 해서 url 따온 다음에 직접 http request날리고 나서 response에서 파싱하면 되지 않나요. 웹 렌더링 되기 전에 response가 어떻게 생겼는지 보지 않아서 뭐라 말하긴 뭐하긴 합니다만

**Comment by Luavis** [comment]
이게 특수한 키를 생성해서 주고 받는 방식이라 webkit같은 remder machine으로 rendering 해서 처리하는 방식이 더 간편할것 같아서 이렇게 진행하고있습니다.

**Comment by toughrogrammer** [comment]
그다지 유쾌한 방식은 아닙니다만 시간표 페이지 들어가서 직접 export 해온 데이터를 파싱하는 방법도 있습니다. 유세인트 강의시간표 파일로 다운로드 받는 기능이 있어요.

**Comment by kyeongwan** [comment]
개인프로젝트로 유세윤과 비슷한 안드로이드 앱을 만들고 있습니다. 정교수님 방식대로 유세인트에서 직접 export 해온 데이터를 파싱하는 방식으로 그냥 간단하게 만들었는데, 프로젝트 완료 후 소스를 공개할 생각이었으니 시간이 된다면 제 서버에서 Open API로 만들어보겠습니다.

**Comment by Luavis** [comment]
파싱은 그렇게 문제가 안되는데..(excel parse라이브러리는 정말 많습니다) 문제가 되고 있는 상황은 crawling해오는것인데요 제가 알기로는 기존의 유세윤이 @growingdever 님이 말씀하신 방식으로 돌아간걸로 아는데 그런부분을 고치는게 개발자가 할 일이 아닌가....싶은데요

**Comment by ghost** [comment]
@Luavis 추천해두신다는게 정확히 어떤의미인가요?

**Comment by Luavis** [comment]
혹시 정통전의 소모임(전자전시회, 로보틱스 등등)이나 주변에 개발로 밥벌어먹고 살겠다는 사람이 좀 있나요?
그런 포부가 있는 사람들에게 이곳을 알려주시면 좋겠습니다~

에 대한 답이였습니다

**Comment by ghost** [comment]
예 감사합니다!

2015년 9월 25일 오후 9:10, Luavis notifications@github.com님이 작성:

> 혹시 정통전의 소모임(전자전시회, 로보틱스 등등)이나 주변에 개발로 밥벌어먹고 살겠다는 사람이 좀 있나요?
> 그런 포부가 있는 사람들에게 이곳을 알려주시면 좋겠습니다~
> 
> 에 대한 답이였습니다
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ssuoss/HelloSSU/issues/7#issuecomment-143199782.

## 

Ministry of National Defence R&D Engineer

Jongchan Kim

+82-10-9781-0031 (Mobile)
